# Generated by Django 6.1.1 on 2026-09-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='標題')),
                ('is_done', models.BooleanField(default=False, verbose_name='已完成')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='截止日')),
            ],
        ),
    ]
